# Travis CI Config
sudo: required
dist: xenial
language: generic

notifications:
  email:
    recipients:
      - dev@uwreact.ca
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=uwreact_robot.rosinstall
  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPO="ros"
    - ROS_DISTRO="kinetic"   ROS_REPO="ros-shadow-fixed"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
